# Properties may be overridden in this optional properties file.
spring.config.import=optional:classpath:env.properties
spring.application.name=avenirs-portfolio-interoperability
spring.profiles.active=prod
server.address=0.0.0.0
server.port=10020
server.url=http://localhost:10020
# Security
security.permit-all-paths=/actuator/prometheus,/actuator/health,/actuator/caches,/avenirs-portfolio-interoperability/api-docs/**,/avenirs-portfolio-interoperability/swagger-ui/**,/favicon.ico,/actuator/health,/error
# Persistence
spring.datasource.url=jdbc:postgresql://localhost:65432/avenirs_interoperability
spring.datasource.username=avenirs_interoperability_admin
spring.datasource.password=ENC(SqPcSCTJpp/z0ipY/oXC/Y1SqO9GB/D+)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=dev
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=false
spring.liquibase.default_schema=dev
# Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1
# jasypt
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator
jasypt.encryptor.password=${jasypt-encryptor-password}
# Prometheus
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/avenirs-portfolio-interoperability/api-docs
springdoc.swagger-ui.path=/avenirs-portfolio-interoperability/swagger-ui
# CORS Configuration
cors.allowed-origins=*
cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
cors.allowed-headers=*
cors.allow-credentials=false
# seeder
seeder.enabled=true
seeder.source=CSV
# Disable spring security - should be removed and use a specific spring filter, to
# check an api key for instance.
spring.security.enabled=false
management.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
security.disabled=true
# hmac (default), dev, disabled, api-key, api-key-or-hmac
security.authentication.filter=api-key-or-hmac
security.authentication.api-key=ENC(tfNG7vGZMGuUCwfLTfcuIcRY6zp5yg3sHsUrG+3Ys7uEOGE+swRhezj4/jmWJzg4dmoGxH6RhMQ=)
# Batch
spring.batch.jdbc.initialize-schema=always
# Opensearch
opensearch.docker.protocol=http
opensearch.docker.host=avenirs-opensearch
opensearch.docker.port=9200
opensearch.health.url=http://avenirs-opensearch:9200/_cluster/health
# Valkey
spring.cache.type=redis
spring.data.redis.host=avenirs-valkey
spring.data.redis.port=6379
# Additional skills
additional.skill.batch.cron=0 0 3 * * WED
france.travail.base.url=https://entreprise.francetravail.fr
rome.4.competence.base.url=https://api.francetravail.io/partenaire/rome-competences/v1/competences
avenirs.microservice.dependency.behaviour=WAIT
avenirs.microservice.dependency.timeout.seconds=600
avenirs.microservice.dependency.retry.interval.seconds=10
