changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
outputFileEncoding=UTF-8
# Reference
referenceUrl=hibernate:spring:fr.avenirsesr.portfolio.interoperability.externalskill.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.interoperability.externalUser.infrastructure.adapter.model?dialect=org.hibernate.dialect.PostgreSQLDialect
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver
# DB
url=jdbc:postgresql://localhost:65432/avenirs_interoperability
username=avenirs_interoperability_admin
password=ENC(SqPcSCTJpp/z0ipY/oXC/Y1SqO9GB/D+)
driver=org.postgresql.Driver
defaultSchemaName=dev
log-level=debug
# Spring batch tables are not managed by liquibase
excludeObjects=table:batch_.*,sequence:batch_.*
